import Head from "next/head";
import dynamic from "next/dynamic";

const Editor = dynamic(() => import("../components/EditorCustom"), {
  ssr: false,
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="editor">
          <Editor />
        </div>
      </main>
    </div>
  );
}
